spring.datasource.url=jdbc:postgresql://localhost:5432/flowcrm
spring.datasource.username=postgres
spring.datasource.password=Pandupandu@12
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# Spring AI + Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:4b
spring.ai.ollama.chat.options.temperature=0.7
